"""empty message

Revision ID: 38647aca04e3
Revises: 8ebb23ca9ebb
Create Date: 2020-09-08 18:00:47.140102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38647aca04e3'
down_revision = '8ebb23ca9ebb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('operator', sa.Boolean(), nullable=True))
    op.drop_column('users', 'verified')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'operator')
    # ### end Alembic commands ###
