"""empty message

Revision ID: 3fc776287c92
Revises: 
Create Date: 2020-08-11 13:19:43.317420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fc776287c92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('committed', sa.Boolean(), nullable=False))
    op.add_column('devices', sa.Column('n_id', sa.String(length=32), nullable=True))
    op.add_column('devices', sa.Column('name', sa.String(length=50), nullable=False))
    op.add_column('devices', sa.Column('network_id', sa.Integer(), nullable=True))
    op.add_column('devices', sa.Column('reg_date', sa.DateTime(), nullable=False))
    op.add_column('devices', sa.Column('serial', sa.String(length=20), nullable=False))
    op.drop_constraint('devices_device_name_key', 'devices', type_='unique')
    op.create_unique_constraint(None, 'devices', ['n_id'])
    op.create_unique_constraint(None, 'devices', ['name'])
    op.drop_constraint('devices_net_id_fkey', 'devices', type_='foreignkey')
    op.create_foreign_key(None, 'devices', 'networks', ['network_id'], ['id'])
    op.drop_column('devices', 'device_name')
    op.drop_column('devices', 'net_id')
    op.drop_column('devices', 'device_serial')
    op.add_column('networks', sa.Column('committed', sa.Boolean(), nullable=False))
    op.add_column('networks', sa.Column('n_id', sa.String(length=32), nullable=True))
    op.add_column('networks', sa.Column('name', sa.String(length=50), nullable=False))
    op.add_column('networks', sa.Column('reg_date', sa.DateTime(), nullable=False))
    op.add_column('networks', sa.Column('type', sa.String(length=30), nullable=False))
    op.add_column('networks', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('networks_net_name_key', 'networks', type_='unique')
    op.create_unique_constraint(None, 'networks', ['name'])
    op.create_unique_constraint(None, 'networks', ['n_id'])
    op.drop_constraint('networks_owner_id_fkey', 'networks', type_='foreignkey')
    op.create_foreign_key(None, 'networks', 'users', ['user_id'], ['id'])
    op.drop_column('networks', 'net_name')
    op.drop_column('networks', 'owner_id')
    op.drop_column('networks', 'net_type')
    op.add_column('templates', sa.Column('reg_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'reg_date')
    op.add_column('networks', sa.Column('net_type', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.add_column('networks', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('networks', sa.Column('net_name', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'networks', type_='foreignkey')
    op.create_foreign_key('networks_owner_id_fkey', 'networks', 'users', ['owner_id'], ['id'])
    op.drop_constraint(None, 'networks', type_='unique')
    op.drop_constraint(None, 'networks', type_='unique')
    op.create_unique_constraint('networks_net_name_key', 'networks', ['net_name'])
    op.drop_column('networks', 'user_id')
    op.drop_column('networks', 'type')
    op.drop_column('networks', 'reg_date')
    op.drop_column('networks', 'name')
    op.drop_column('networks', 'n_id')
    op.drop_column('networks', 'committed')
    op.add_column('devices', sa.Column('device_serial', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.add_column('devices', sa.Column('net_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('devices', sa.Column('device_name', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.create_foreign_key('devices_net_id_fkey', 'devices', 'networks', ['net_id'], ['id'])
    op.drop_constraint(None, 'devices', type_='unique')
    op.drop_constraint(None, 'devices', type_='unique')
    op.create_unique_constraint('devices_device_name_key', 'devices', ['device_name'])
    op.drop_column('devices', 'serial')
    op.drop_column('devices', 'reg_date')
    op.drop_column('devices', 'network_id')
    op.drop_column('devices', 'name')
    op.drop_column('devices', 'n_id')
    op.drop_column('devices', 'committed')
    # ### end Alembic commands ###
