"""empty message

Revision ID: a30d2eaedc97
Revises: eac610d66c04
Create Date: 2020-09-04 20:22:18.218966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a30d2eaedc97'
down_revision = 'eac610d66c04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('grptag',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'tag_id')
    )
    op.create_table('nettag',
    sa.Column('net_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['net_id'], ['networks.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('net_id', 'tag_id')
    )
    op.add_column('networks', sa.Column('net_tags', sa.String(length=256), nullable=True))
    op.drop_column('networks', 'tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('networks', sa.Column('tags', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_column('networks', 'net_tags')
    op.drop_table('nettag')
    op.drop_table('grptag')
    op.drop_table('tags')
    # ### end Alembic commands ###
