"""empty message

Revision ID: af2ae1722532
Revises: e5d001ab348f
Create Date: 2020-09-25 12:41:07.599104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af2ae1722532'
down_revision = 'e5d001ab348f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('networks', sa.Column('source_network', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'networks', 'networks', ['source_network'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'networks', type_='foreignkey')
    op.drop_column('networks', 'source_network')
    # ### end Alembic commands ###
