"""empty message

Revision ID: b1134f4b84c8
Revises: a30d2eaedc97
Create Date: 2020-09-05 14:04:04.362547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1134f4b84c8'
down_revision = 'a30d2eaedc97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('templates_template_user_fkey', 'templates', type_='foreignkey')
    op.drop_column('templates', 'template_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('template_user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('templates_template_user_fkey', 'templates', 'users', ['template_user'], ['id'])
    # ### end Alembic commands ###
