"""empty message

Revision ID: d15b360e4132
Revises: 3fc776287c92
Create Date: 2020-08-11 13:32:54.650185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd15b360e4132'
down_revision = '3fc776287c92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('templates_user_id_fkey', 'templates', type_='foreignkey')
    op.drop_column('templates', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('templates_user_id_fkey', 'templates', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
