"""empty message

Revision ID: e5d001ab348f
Revises: 71cf60159f25
Create Date: 2020-09-10 17:00:21.524839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5d001ab348f'
down_revision = '71cf60159f25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('devmodel', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'devmodel')
    # ### end Alembic commands ###
